import Link from "next/link";
import { ArrowRight, ArrowUpRight, FileSearch, FolderOpen, MessageSquare, PenLine, Compass, BookOpen, Scale, FileText, LockKeyhole, Check } from "lucide-react";
export default function Home() {
  return <div className="home-workspace">
    <div className="home-intro"><div><p className="welcome-line">Your legal workspace</p><h1>A clearer way forward.</h1><p>Understand your situation. Organize your case. Take the next step.</p></div><Link href="/cases" className="btn-secondary"><FolderOpen size={17}/>Open my cases</Link></div>
    <section className="start-panel" aria-labelledby="start-title">
      <div className="start-copy"><span className="start-symbol"><Scale size={24}/></span><h2 id="start-title">Received a legal notice?<br/>Start with understanding it.</h2><p>Turn a complicated notice into a plain-language summary, key points and questions to discuss with your advocate.</p><Link className="btn-primary" href="/victim-citizen"><FileSearch size={18}/>Understand my notice<ArrowRight size={17}/></Link><span className="start-note">Use the tool directly. Save to a case when you’re ready.</span></div>
      <div className="notice-preview" aria-label="Illustration of a notice and a plain-language summary"><div className="paper-sheet"><span className="paper-caption"><FileText size={17}/>Legal notice</span><div className="paper-line long"/><div className="paper-line"/><div className="paper-line short"/><div className="paper-highlight"><div className="paper-line long"/><div className="paper-line"/></div><div className="paper-line"/><div className="paper-line short"/><div className="paper-seal"><Scale size={24}/></div></div><div className="summary-preview"><span><Check size={15}/>A little easier to understand</span><p>What does it say?</p><p>What should I review?</p><p>What can I do next?</p></div><span className="preview-label">From legal language to a clear next step</span></div>
    </section>
    <section className="home-tools" aria-labelledby="quick-tools"><div className="section-heading"><h2 id="quick-tools">How can we help?</h2><Link href="/tools">Explore all tools<ArrowRight size={16}/></Link></div><div className="quick-tools">
      {[{title:"Ask a legal question",body:"Talk it through by voice or text.",href:"/citizen/voice-assistant",icon:MessageSquare},{title:"Prepare a document",body:"Create a first draft for review.",href:"/advocate?tool=drafting",icon:PenLine},{title:"Find legal support",body:"Explore lawyers and free legal aid.",href:"/citizen#legal-aid",icon:Compass},{title:"Research the law",body:"Find sections, precedents and judgments.",href:"/advocate/precedents",icon:BookOpen}].map(({title,body,href,icon:Icon}) => <Link href={href} className="quick-tool" key={title}><span className="tool-icon"><Icon size={21}/></span><h3>{title}</h3><p>{body}</p><ArrowUpRight className="quick-arrow" size={17}/></Link>)}
    </div></section>
    <section className="case-intro"><div className="case-illustration" aria-hidden="true"><FolderOpen size={42} strokeWidth={1.3}/><span><LockKeyhole size={15}/></span></div><div><h2>One case. Everything in its place.</h2><p>Keep original documents, conversations and drafts together. Track next steps and choose what to share with your advocate.</p><Link href="/cases">Set up your case workspace<ArrowRight size={16}/></Link></div><div className="case-features"><span><Check size={16}/>Documents and versions</span><span><Check size={16}/>Tasks and reviewed drafts</span><span><Check size={16}/>Sharing you control</span></div></section>
    <div className="home-paths"><Link href="/citizen"><span>Looking for guidance?</span><strong>Explore citizen tools <ArrowRight size={16}/></strong></Link><Link href="/advocate"><span>Working on a client’s matter?</span><strong>Open advocate tools <ArrowRight size={16}/></strong></Link></div>
  </div>;
}
