"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, FileSearch, FolderOpen, MessageSquare, PenLine, Compass, BookOpen, Scale, FileText, LockKeyhole, Check } from "lucide-react";
import { usePreferences } from "@/components/PreferencesProvider";
import { LanguageSelector } from "@/components/PreferenceControls";
export default function Home() {
  const { t } = usePreferences();
  return <div className="home-workspace">
    <div className="home-intro"><div><p className="welcome-line">{t("Your legal workspace")}</p><h1>{t("A clearer way forward.")}</h1><p>{t("Understand your situation. Organize your case. Take the next step.")}</p></div><div className="home-preferences"><LanguageSelector prominent/><Link href="/cases" className="btn-secondary"><FolderOpen size={17}/>{t("My cases")}</Link></div></div>
    <section className="start-panel" aria-labelledby="start-title">
      <div className="start-copy"><span className="start-symbol"><Scale size={24}/></span><h2 id="start-title">{t("Received a legal notice?")}<br/>{t("Start with understanding it.")}</h2><p>{t("Get a plain-language summary and questions to discuss with your advocate.")}</p><Link className="btn-primary" href="/victim-citizen"><FileSearch size={18}/>{t("Understand a notice")}<ArrowRight size={17}/></Link><span className="start-note">{t("Use the tool directly. Save to a case when you’re ready.")}</span></div>
      <div className="notice-preview" aria-hidden="true"><div className="paper-sheet"><span className="paper-caption"><FileText size={17}/>{t("Legal notice")}</span><div className="paper-line long"/><div className="paper-line"/><div className="paper-line short"/><div className="paper-highlight"><div className="paper-line long"/><div className="paper-line"/></div><div className="paper-line"/><div className="paper-line short"/><div className="paper-seal"><Scale size={24}/></div></div><div className="summary-preview"><span><Check size={15}/>{t("A little easier to understand")}</span><p>{t("What does it say?")}</p><p>{t("What should I review?")}</p><p>{t("What can I do next?")}</p></div></div>
    </section>
    <section className="home-tools" aria-labelledby="quick-tools"><div className="section-heading"><h2 id="quick-tools">{t("How can we help?")}</h2><Link href="/tools">{t("All tools")}<ArrowRight size={16}/></Link></div><div className="quick-tools">
      {[{title:"Talk to the assistant",body:"Ask questions by voice or text.",href:"/citizen/voice-assistant",icon:MessageSquare},{title:"Draft a document",body:"Prepare a first draft for review.",href:"/advocate?tool=drafting",icon:PenLine},{title:"Free legal aid",body:"Find clinics and legal aid resources.",href:"/citizen#legal-aid",icon:Compass},{title:"Precedents & judgments",body:"Browse research and Indian Kanoon links.",href:"/advocate/precedents",icon:BookOpen}].map(({title,body,href,icon:Icon}) => <Link href={href} className="quick-tool" key={title}><span className="tool-icon"><Icon size={21}/></span><h3>{t(title)}</h3><p>{t(body)}</p><ArrowUpRight className="quick-arrow" size={17}/></Link>)}
    </div></section>
    <section className="case-intro"><div className="case-illustration" aria-hidden="true"><FolderOpen size={42} strokeWidth={1.3}/><span><LockKeyhole size={15}/></span></div><div><h2>{t("One case. Everything in its place.")}</h2><p>{t("Keep your documents, conversations and drafts together.")}</p><Link href="/cases">{t("My cases")}<ArrowRight size={16}/></Link></div><div className="case-features"><span><Check size={16}/>{t("Documents and versions")}</span><span><Check size={16}/>{t("Tasks and reviewed drafts")}</span><span><Check size={16}/>{t("Sharing you control")}</span></div></section>
    <div className="home-paths"><Link href="/citizen"><span>{t("Get legal help")}</span><strong>{t("Citizen tools")} <ArrowRight size={16}/></strong></Link><Link href="/advocate"><span>{t("For your practice")}</span><strong>{t("Advocate tools")} <ArrowRight size={16}/></strong></Link></div>
  </div>;
}
