// ─────────────────────────────────────────────────────────────
//  IPC (1860) ↔ BNS (2023) sample mapping dataset.
//
//  ⚠️ DEMO DATASET — curated subset, not exhaustive. Verify every
//  mapping against the official BNS 2023 text before any real use.
//  Source for cross-checking: https://documents.gov.in (BNS 2023 PDF).
// ─────────────────────────────────────────────────────────────

import type { CodeMapping } from "@/types";

export const ipcBnsData: CodeMapping[] = [
  {
    ipcSection: "302",
    ipcTitle: "Punishment for murder",
    bnsSection: "103",
    bnsTitle: "Punishment for murder",
    description: "Causing death of a person with the intention of killing them.",
    category: "Offences against the body",
  },
  {
    ipcSection: "304",
    ipcTitle: "Punishment for culpable homicide not amounting to murder",
    bnsSection: "105",
    bnsTitle: "Punishment for culpable homicide not amounting to murder",
    description: "Causing death with intent but under mitigating circumstances.",
    category: "Offences against the body",
  },
  {
    ipcSection: "304A",
    ipcTitle: "Causing death by negligence",
    bnsSection: "106",
    bnsTitle: "Causing death or severe injury by negligent or rash act",
    description: "Rash or negligent act causing death (e.g. road accidents).",
    category: "Offences against the body",
  },
  {
    ipcSection: "304B",
    ipcTitle: "Dowry death",
    bnsSection: "80",
    bnsTitle: "Dowry death",
    description: "Death of a woman from burn or injury within 7 years of marriage linked to dowry.",
    category: "Offences against women",
  },
  {
    ipcSection: "354",
    ipcTitle: "Assault on woman with intent to outrage modesty",
    bnsSection: "74",
    bnsTitle: "Assault or use of criminal force with intent to outrage modesty",
    description: "Using force on a woman to insult or outrage her modesty.",
    category: "Offences against women",
  },
  {
    ipcSection: "375",
    ipcTitle: "Rape",
    bnsSection: "63",
    bnsTitle: "Rape",
    description: "Non-consensual sexual intercourse as legally defined.",
    category: "Sexual offences",
  },
  {
    ipcSection: "376",
    ipcTitle: "Punishment for rape",
    bnsSection: "64",
    bnsTitle: "Punishment for rape",
    description: "Punishment prescribed for the offence of rape.",
    category: "Sexual offences",
  },
  {
    ipcSection: "392",
    ipcTitle: "Punishment for robbery",
    bnsSection: "112",
    bnsTitle: "Punishment for robbery / Snatching",
    description: "Taking property by force or fear.",
    category: "Offences against property",
  },
  {
    ipcSection: "415",
    ipcTitle: "Cheating",
    bnsSection: "318",
    bnsTitle: "Cheating",
    description: "Deceiving someone to deliver property or cause harm.",
    category: "Offences against property",
  },
  {
    ipcSection: "420",
    ipcTitle: "Cheating and dishonestly inducing delivery of property",
    bnsSection: "318(2)",
    bnsTitle: "Cheating (punishment for dishonouring a cheque or inducing delivery)",
    description: "Classic fraud/scam — induced delivery of property by deception.",
    category: "Offences against property",
  },
  {
    ipcSection: "378",
    ipcTitle: "Theft",
    bnsSection: "303",
    bnsTitle: "Theft",
    description: "Moving property with dishonest intent to take it from its owner.",
    category: "Offences against property",
  },
  {
    ipcSection: "379",
    ipcTitle: "Punishment for theft",
    bnsSection: "303(2)",
    bnsTitle: "Theft",
    description: "Standard punishment for theft of movable property.",
    category: "Offences against property",
  },
  {
    ipcSection: "435",
    ipcTitle: "Mischief by fire or explosive substance",
    bnsSection: "325",
    bnsTitle: "Mischief by fire / explosive",
    description: "Arson or property destruction by incendiary means.",
    category: "Offences against property",
  },
  {
    ipcSection: "442",
    ipcTitle: "House trespass",
    bnsSection: "329",
    bnsTitle: "House-trespass",
    description: "Unlawfully entering someone's house or property.",
    category: "Offences against property",
  },
  {
    ipcSection: "499",
    ipcTitle: "Defamation",
    bnsSection: "356",
    bnsTitle: "Defamation",
    description: "Harming the reputation of a person via words, signs, or visible representation.",
    category: "Offences against reputation",
  },
  {
    ipcSection: "500",
    ipcTitle: "Punishment for defamation",
    bnsSection: "356(2)",
    bnsTitle: "Punishment for defamation",
    description: "Standard punishment for criminal defamation.",
    category: "Offences against reputation",
  },
  {
    ipcSection: "503",
    ipcTitle: "Criminal intimidation",
    bnsSection: "351",
    bnsTitle: "Criminal intimidation",
    description: "Threatening injury or harm to frighten someone into acting.",
    category: "Offences against the person/reputation",
  },
  {
    ipcSection: "506",
    ipcTitle: "Punishment for criminal intimidation",
    bnsSection: "351(2)",
    bnsTitle: "Punishment for criminal intimidation",
    description: "Punishment scale tied to the threatened harm.",
    category: "Offences against the person/reputation",
  },
  {
    ipcSection: "153A",
    ipcTitle: "Promoting enmity between groups on grounds of religion, race, etc.",
    bnsSection: "196",
    bnsTitle: "Promoting enmity between groups",
    description: "Acts prejudicial to harmony between communities.",
    category: "Offences against public tranquility",
  },
  {
    ipcSection: "141",
    ipcTitle: "Unlawful assembly",
    bnsSection: "189",
    bnsTitle: "Unlawful assembly",
    description: "Five+ persons assembled for an illegal purpose.",
    category: "Offences against public tranquility",
  },
  {
    ipcSection: "120B",
    ipcTitle: "Punishment for criminal conspiracy",
    bnsSection: "61",
    bnsTitle: "Criminal conspiracy",
    description: "Agreement by 2+ persons to commit an illegal act.",
    category: "Abetment & conspiracy",
  },
  {
    ipcSection: "511",
    ipcTitle: "Punishment for attempting to commit offences",
    bnsSection: "236 / 237",
    bnsTitle: "Attempt to commit suicide / offence",
    description: "Punishment when an offence is attempted but not completed.",
    category: "Attempts & abetment",
  },
];
